[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Ray Kell <raymond.kell@spaceforce.mil"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"